2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_setup.py:_flush():67] Configure stats pid to 70129
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_setup.py:_flush():67] Loading settings from /root/workspace/college-math/mxm/RL4DA_MXM/enkf_L63/wandb/settings
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /root/workspace/college-math/mxm/RL4DA_MXM/enkf_L63/wandb/run-20250407_220250-98gwhiyi/logs/debug.log
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /root/workspace/college-math/mxm/RL4DA_MXM/enkf_L63/wandb/run-20250407_220250-98gwhiyi/logs/debug-internal.log
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_init.py:init():781] calling init triggers
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'policy_type': 'PPO-shared', 'total_timesteps': 10000000, 'env_name': 'L63-ENKF', '_wandb': {}}
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_init.py:init():809] starting backend
2025-04-07 22:02:50,112 INFO    MainThread:70129 [wandb_init.py:init():813] sending inform_init request
2025-04-07 22:02:50,116 INFO    MainThread:70129 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-07 22:02:50,116 INFO    MainThread:70129 [wandb_init.py:init():823] backend started and connected
2025-04-07 22:02:50,117 INFO    MainThread:70129 [wandb_init.py:init():915] updated telemetry
2025-04-07 22:02:50,123 INFO    MainThread:70129 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-07 22:02:50,778 INFO    MainThread:70129 [wandb_init.py:init():1014] starting run threads in backend
2025-04-07 22:02:51,024 INFO    MainThread:70129 [wandb_run.py:_console_start():2454] atexit reg
2025-04-07 22:02:51,024 INFO    MainThread:70129 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-07 22:02:51,024 INFO    MainThread:70129 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-07 22:02:51,024 INFO    MainThread:70129 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-07 22:02:51,026 INFO    MainThread:70129 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-07 22:02:51,925 INFO    MainThread:70129 [wandb_run.py:_config_callback():1327] config_cb None None {'algo': 'PPO', 'policy_class': "<class '__main__.CustomMLPPolicy'>", 'device': 'cpu', 'verbose': 1, 'policy_kwargs': '{}', 'num_timesteps': 0, '_total_timesteps': 10000000, '_num_timesteps_at_start': 0, 'seed': 'None', 'action_noise': 'None', 'start_time': 1744081371913054173, 'learning_rate': 0.0003, 'tensorboard_log': 'runs/98gwhiyi', '_last_obs': '[[ -1.4726838   3.041061   26.063934   -6.455393  -10.372021   16.655146\n   45.137447   -5.8922744 -73.982346 ]]', '_last_episode_starts': '[ True]', '_last_original_obs': 'None', '_episode_num': 0, 'use_sde': 'False', 'sde_sample_freq': -1, '_current_progress_remaining': 1.0, '_stats_window_size': 100, 'ep_info_buffer': 'deque([], maxlen=100)', 'ep_success_buffer': 'deque([], maxlen=100)', '_n_updates': 0, '_custom_logger': 'False', 'env': '<stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fc38fdb1040>', '_vec_normalize_env': 'None', 'observation_space': 'Box(-50.0, 50.0, (9,), float32)', 'action_space': 'Box(-50.0, 50.0, (3,), float32)', 'n_envs': 1, 'n_steps': 2048, 'gamma': 0.99, 'gae_lambda': 0.95, 'ent_coef': 0.0, 'vf_coef': 0.5, 'max_grad_norm': 0.5, 'rollout_buffer_class': "<class 'stable_baselines3.common.buffers.RolloutBuffer'>", 'rollout_buffer_kwargs': '{}', 'batch_size': 64, 'n_epochs': 10, 'clip_range': '<function get_schedule_fn.<locals>.<lambda> at 0x7fc372eaba60>', 'clip_range_vf': 'None', 'normalize_advantage': 'True', 'target_kl': 'None', 'lr_schedule': '<function get_schedule_fn.<locals>.<lambda> at 0x7fc38e8953a0>', 'rollout_buffer': '<stable_baselines3.common.buffers.RolloutBuffer object at 0x7fc38fa63c50>', 'policy': 'CustomMLPPolicy(\n  (features_extractor): FeatureExtractor(\n    (net): Sequential(\n      (0): Linear(in_features=9, out_features=32, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=32, out_features=16, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=16, out_features=8, bias=True)\n      (5): ReLU()\n    )\n  )\n  (pi_features_extractor): FeatureExtractor(\n    (net): Sequential(\n      (0): Linear(in_features=9, out_features=32, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=32, out_features=16, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=16, out_features=8, bias=True)\n      (5): ReLU()\n    )\n  )\n  (vf_features_extractor): FeatureExtractor(\n    (net): Sequential(\n      (0): Linear(in_features=9, out_features=32, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=32, out_features=16, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=16, out_features=8, bias=True)\n      (5): ReLU()\n    )\n  )\n  (mlp_extractor): IdentityMLPExtractor()\n  (action_net): Linear(in_features=8, out_features=3, bias=True)\n  (value_net): Linear(in_features=8, out_features=1, bias=True)\n)', '_logger': '<stable_baselines3.common.logger.Logger object at 0x7fc3731978c0>'}
2025-04-07 22:03:45,031 INFO    MsgRouterThr:70129 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-07 22:03:45,172 ERROR   Thread-5  :70129 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 22:03:45,284 ERROR   Thread-5  :70129 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 22:03:45,390 ERROR   Thread-5  :70129 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-04-07 22:03:45,495 ERROR   Thread-5  :70129 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/root/miniconda3/envs/main/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
